### ISSUE TITLE
Hexo分支无法使用

### ISSUE THREAD

**Issue by Ellean** [houyi1121/Playing-reward#2]
本来想给博客怎天点新东西，奈何我本来就不是做网页的，改了一晚上BUG……还没改完我就要赶高铁去了，已fork，回去再改。甚至尝试你网页的源码直接帮过去，不见效

**Comment by ihoey** [comment]
为啥我现在才看见这个 issues 😰😰

**Comment by callmesoul** [comment]
@Ellean 
@ihoey 
我自己封装了个
https://github.com/callmesoul/js-reward
